"""
LAMMPS calculator implementation for GRIP.

This module wraps LAMMPS as a calculator backend, maintaining compatibility
with the original GRIP workflow while conforming to the new Calculator interface.
"""

import os
import shutil
from subprocess import Popen, PIPE, getstatusoutput
from typing import Optional, Tuple

import numpy as np
from ase import Atoms
from ase.io import write as ase_write
from ase.io.lammpsrun import read_lammps_dump
from ase.io.lammpsdata import write_lammps_data

from core.calculator import Calculator, CalculationResult


class LAMMPSCalculator(Calculator):
    """
    Calculator that interfaces with LAMMPS for energy evaluation and relaxation.
    
    This calculator:
    1. Writes structures in LAMMPS data format
    2. Runs LAMMPS with specified potential
    3. Parses energy from LAMMPS output
    4. Supports both relaxation and MD
    
    The relax_structure method runs LAMMPS minimization and returns both
    the relaxed structure AND the final energy.
    """
    
    def __init__(
        self,
        binary: str,
        pair_style: str,
        pair_coeff: str,
        mass: float,
        units: str = "metal",
        boundary: str = "p p s",
        minimize_style: str = "cg",
        minimize_params: str = "1e-15 1e-15 100000 100000",
        working_dir: Optional[str] = None,
    ):
        """
        Initialize LAMMPS calculator.
        
        Args:
            binary: Path to LAMMPS executable (or command name if in PATH)
            pair_style: LAMMPS pair_style command (e.g., 'eam/alloy', 'meam/spline')
            pair_coeff: LAMMPS pair_coeff arguments (e.g., '* * pot.eam Cu')
            mass: Atomic mass for the species
            units: LAMMPS units (default: 'metal' for eV, Angstrom)
            boundary: LAMMPS boundary conditions (default: 'p p s')
            minimize_style: Minimization algorithm (default: 'cg')
            minimize_params: Minimization parameters
            working_dir: Directory for LAMMPS files (default: current directory)
        """
        self.binary = binary
        self.pair_style = pair_style
        self.pair_coeff = pair_coeff
        self.mass = mass
        self.units = units
        self.boundary = boundary
        self.minimize_style = minimize_style
        self.minimize_params = minimize_params
        self.working_dir = working_dir or os.getcwd()
        
        # Verify LAMMPS is available
        self._lammps_available = None
    
    def _check_lammps(self) -> bool:
        """Check if LAMMPS is available."""
        if self._lammps_available is None:
            self._lammps_available = (
                os.path.exists(self.binary) or 
                getstatusoutput(f"{self.binary} -h")[0] == 0
            )
        return self._lammps_available
    
    def _write_input_relax(self, input_file: str, data_file: str, 
                           output_file: str, bounds: Optional[Tuple] = None) -> None:
        """Write LAMMPS input script for relaxation."""
        
        # Set up region definitions if bounds provided
        if bounds is not None:
            lowerb, upperb, pad = bounds
            region_setup = f"""
# Define regions for GB calculation
variable    Lower1 equal "bound(all, zmin) + {lowerb}"
variable    Upper1 equal "bound(all, zmax) - {upperb}"

region      lowlayer block INF INF INF INF INF ${{Lower1}} units box
group       lowlayer region lowlayer

region      gbregion block INF INF INF INF ${{Lower1}} ${{Upper1}} units box
group       gbregion region gbregion

region      uplayer block INF INF INF INF ${{Upper1}} INF units box
group       uplayer region uplayer

# Fix boundary layers
fix         f1 lowlayer setforce 0.0 0.0 0.0
fix         f2 uplayer aveforce 0.0 0.0 0.0
"""
        else:
            region_setup = ""
        
        script = f"""# LAMMPS input for relaxation - generated by GRIP
clear
units       {self.units}
dimension   3
boundary    {self.boundary}
atom_style  atomic

# Read structure
read_data   {data_file}
mass        * {self.mass}

# Define potential
pair_style  {self.pair_style}
pair_coeff  {self.pair_coeff}

neighbor        2.0 bin
neigh_modify    delay 10 check yes

{region_setup}

# Run minimization
min_style   {self.minimize_style}
minimize    {self.minimize_params}

# Compute energies
compute     eng all pe/atom
compute     etotal all reduce sum c_eng

# Output
thermo_style    custom step pe lx ly lz press
dump        d1 all custom 1 {output_file} id type x y z c_eng
dump_modify d1 sort id
run 0

# Print final energy
variable    Etot equal "c_etotal"
print "ENERGY = ${{Etot}}" append {output_file}
"""
        with open(input_file, 'w') as f:
            f.write(script)
    
    def _write_input_md(self, input_file: str, data_file: str, output_file: str,
                        temperature: float, steps: int, seed: int = 12345,
                        bounds: Optional[Tuple] = None) -> None:
        """Write LAMMPS input script for MD + relaxation."""
        
        if bounds is not None:
            lowerb, upperb, pad = bounds
            region_setup = f"""
# Define regions
variable    Lower1 equal "bound(all, zmin) + {lowerb}"
variable    Upper1 equal "bound(all, zmax) - {upperb}"

region      lowlayer block INF INF INF INF INF ${{Lower1}} units box
group       lowlayer region lowlayer

region      gbregion block INF INF INF INF ${{Lower1}} ${{Upper1}} units box
group       gbregion region gbregion

region      uplayer block INF INF INF INF ${{Upper1}} INF units box
group       uplayer region uplayer

fix         f1 lowlayer setforce 0.0 0.0 0.0
fix         f2 uplayer aveforce 0.0 0.0 0.0
"""
            md_group = "gbregion"
        else:
            region_setup = ""
            md_group = "all"
        
        T_init = temperature * 2  # Start higher for equilibration
        T_final = 50  # Cool down temperature
        
        script = f"""# LAMMPS input for MD + relaxation - generated by GRIP
clear
units       {self.units}
dimension   3
boundary    {self.boundary}
atom_style  atomic

read_data   {data_file}
mass        * {self.mass}

pair_style  {self.pair_style}
pair_coeff  {self.pair_coeff}

neighbor        1.0 bin
neigh_modify    every 1 delay 1 check yes

{region_setup}

# Initial minimization
min_style   {self.minimize_style}
minimize    1e-15 1e-15 100000 100000

# MD at temperature
velocity    {md_group} create {T_init} {seed} dist gaussian rot yes
fix         r1 all nve
fix         r2 {md_group} langevin {temperature} {temperature} $(100*dt) {seed}

timestep    0.002
run         {steps}

# Cool down
unfix       r2
fix         r3 {md_group} langevin {temperature} {T_final} $(100*dt) {seed}
run         1000

# Final relaxation
unfix       r1
unfix       r3
min_style   {self.minimize_style}
minimize    {self.minimize_params}

# Output
compute     eng all pe/atom
compute     etotal all reduce sum c_eng
thermo_style    custom step pe lx ly lz
dump        d1 all custom 1 {output_file} id type x y z c_eng
dump_modify d1 sort id
run 0

variable    Etot equal "c_etotal"
print "ENERGY = ${{Etot}}" append {output_file}
"""
        with open(input_file, 'w') as f:
            f.write(script)
    
    def _run_lammps(self, input_file: str, log_file: str = "log.lammps") -> bool:
        """Run LAMMPS and return success status."""
        cmd = [self.binary, "-i", input_file, "-log", log_file]
        proc = Popen(cmd, stdout=PIPE, stderr=PIPE)
        stdout, stderr = proc.communicate()
        return proc.returncode == 0
    
    def _parse_energy(self, output_file: str) -> float:
        """Parse energy from LAMMPS output file."""
        with open(output_file, 'rb') as f:
            try:
                f.seek(-2, os.SEEK_END)
                while f.read(1) != b'\n':
                    f.seek(-2, os.SEEK_CUR)
            except OSError:
                f.seek(0)
            last_line = f.readline().decode().strip()
        
        # Format: "ENERGY = X.XXX"
        if last_line.startswith("ENERGY"):
            tokens = last_line.split('=')
            return float(tokens[1].strip())
        else:
            raise ValueError(f"Could not parse energy from: {last_line}")
    
    def _read_structure(self, output_file: str, symbol: str = None) -> Atoms:
        """Read relaxed structure from LAMMPS dump file."""
        atoms = read_lammps_dump(output_file)
        
        # Fix chemical symbols if needed
        if symbol and len(set(atoms.get_chemical_symbols())) == 1:
            for a in atoms:
                a.symbol = symbol
        
        return atoms
    
    def calculate_energy(self, atoms: Atoms, bounds: Optional[Tuple] = None,
                        **kwargs) -> CalculationResult:
        """
        Single-point energy calculation (minimization without MD).
        
        Args:
            atoms: ASE Atoms object
            bounds: Optional (lowerb, upperb, pad) for GB region definition
            
        Returns:
            CalculationResult with energy and minimized structure
        """
        if not self._check_lammps():
            raise RuntimeError(f"LAMMPS not found at: {self.binary}")
        
        # File paths
        data_file = os.path.join(self.working_dir, "structure.data")
        input_file = os.path.join(self.working_dir, "lammps.in")
        output_file = os.path.join(self.working_dir, "lammps_out")
        
        # Write structure
        write_lammps_data(data_file, atoms)
        
        # Write and run LAMMPS
        self._write_input_relax(input_file, data_file, output_file, bounds)
        success = self._run_lammps(input_file)
        
        if not success:
            return CalculationResult(
                atoms=atoms,
                energy=float('inf'),
                converged=False,
                metadata={'error': 'LAMMPS calculation failed'}
            )
        
        # Parse results
        energy = self._parse_energy(output_file)
        relaxed_atoms = self._read_structure(output_file)
        
        return CalculationResult(
            atoms=relaxed_atoms,
            energy=energy,
            converged=True,
            metadata={'calculator': 'LAMMPS', 'type': 'single_point'}
        )
    
    def relax_structure(self, atoms: Atoms, bounds: Optional[Tuple] = None,
                       **kwargs) -> CalculationResult:
        """
        Relax structure using LAMMPS minimization.
        
        Returns BOTH the relaxed structure AND the energy.
        
        Args:
            atoms: ASE Atoms object
            bounds: Optional (lowerb, upperb, pad) for GB region
            
        Returns:
            CalculationResult with relaxed atoms and final energy
        """
        # For LAMMPS, single-point includes minimization
        return self.calculate_energy(atoms, bounds=bounds, **kwargs)
    
    def run_md(self, atoms: Atoms, temperature: float, steps: int,
               bounds: Optional[Tuple] = None, seed: int = 12345,
               **kwargs) -> CalculationResult:
        """
        Run MD at finite temperature followed by relaxation.
        
        This implements the GRIP workflow: high-T MD -> cooling -> minimization.
        Returns BOTH the final structure AND energy.
        
        Args:
            atoms: ASE Atoms object
            temperature: MD temperature in Kelvin
            steps: Number of MD steps
            bounds: Optional (lowerb, upperb, pad) for GB region
            seed: Random seed for velocities
            
        Returns:
            CalculationResult with final structure and energy
        """
        if not self._check_lammps():
            raise RuntimeError(f"LAMMPS not found at: {self.binary}")
        
        # File paths
        data_file = os.path.join(self.working_dir, "structure.data")
        input_file = os.path.join(self.working_dir, "lammps_md.in")
        output_file = os.path.join(self.working_dir, "lammps_md_out")
        
        # Write structure
        write_lammps_data(data_file, atoms)
        
        # Write and run LAMMPS MD
        self._write_input_md(input_file, data_file, output_file, 
                            temperature, steps, seed, bounds)
        success = self._run_lammps(input_file, log_file="log.lammps_md")
        
        if not success:
            return CalculationResult(
                atoms=atoms,
                energy=float('inf'),
                converged=False,
                metadata={'error': 'LAMMPS MD failed'}
            )
        
        # Parse results
        energy = self._parse_energy(output_file)
        final_atoms = self._read_structure(output_file)
        
        return CalculationResult(
            atoms=final_atoms,
            energy=energy,
            converged=True,
            metadata={
                'calculator': 'LAMMPS',
                'type': 'md',
                'temperature': temperature,
                'steps': steps
            }
        )
    
    def supports_md(self) -> bool:
        """LAMMPS supports MD."""
        return True
    
    def __repr__(self):
        return f"LAMMPSCalculator(binary={self.binary}, pair_style={self.pair_style})"
